version: '2'

services:
  webserver:
    build: ./.docker/webserver
    image: xpress_health
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html:z
    links:
      - db

  db:
    image: mariadb:10.3
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER= xpress_admin
      - MYSQL_PASSWORD=leyvosYRnFHPujCH
      - MYSQL_DATABASE=xpress_health

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER= xpress_admin
      - MYSQL_PASSWORD=leyvosYRnFHPujCH
